name: aggressor_adventures
description: A flutter application for the Aggressor Adventures

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  sqflite: ^1.0.0
  path_provider: ^2.0.2
  async: ^2.5.0
  flutter_cache_manager: ^2.1.2
  date_format: ^2.0.2
  url_launcher: ^6.0.4
  multi_image_picker: ^4.8.0
  permission_handler: ^8.0.0+2
  flutter_aws_s3_client: ^0.5.2
  flutter_absolute_path: ^1.0.6
  chunked_stream: ^1.4.1
  file_picker: ^3.0.2
  persistent_bottom_nav_bar: ^4.0.2
  cached_network_image: ^2.5.1
  flutter_map: any
  image_downloader: ^0.30.0
  cupertino_icons: ^1.0.2
  percent_indicator: ^2.1.3
  wakelock: ^0.2.1
  heic_to_jpg: ^0.1.3
  open_file: ^3.2.1
  flutter_launcher_icons: ^0.8.0
  flutter_html: ^1.0.0
  html_editor_enhanced: ^2.1.1
  flutter_masked_text: ^0.8.0
  data_connection_checker: ^0.3.4
  flutter_slidable: ^0.6.0
  flutter_archive: ^4.0.1
  auto_size_text: ^2.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appicon.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true



  assets:
    - assets/tripsactive.png
    - assets/tripspassive.png
    - assets/notesactive.png
    - assets/notespassive.png
    - assets/photosactive.png
    - assets/photospassive.png
    - assets/rewardsactive.png
    - assets/rewardspassive.png
    - assets/filesactive.png
    - assets/filespassive.png
    - assets/notesblue.png
    - assets/photosblue.png
    - assets/addphotosblue.png
    - assets/filesblue.png
    - assets/logo.png
    - assets/loginbackground.png
    - assets/pagebackground.png
    - assets/bannerimage.png
    - assets/adventureclub.png
    - assets/callicon.png
    - assets/menuicon.png
    - assets/certification.png
    - assets/divemilestone.png
    - assets/filearrow.png
    - assets/irondiver.png
    - assets/leftarrow.png
    - assets/rightarrow.png
    - assets/noprofile.png
    - assets/redquestion.png
    - assets/trashcan.png
    - assets/vipclub.png
    - assets/vipplusclub.png
    - assets/redflag.png
    - assets/sevenseasclub.png
