name: aggressor_adventures
description: A flutter application for the Aggressor Adventures

publish_to: "none"
version: 4.0.2+43

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http:
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  async: ^2.11.0
  flutter_cache_manager: ^3.3.1
  date_format: ^2.0.7
  url_launcher: ^6.2.6
  # multi_image_picker: any
  permission_handler: ^11.3.1
  flutter_aws_s3_client:
  chunked_stream: ^1.4.2
  file_picker:
  cached_network_image: ^3.3.1
  flutter_map:
  percent_indicator: ^4.2.3
  wakelock:
  open_file: ^3.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_html:
  html_editor_enhanced: ^2.5.1
  flutter_slidable: ^3.0.1
  flutter_archive: ^6.0.0
  auto_size_text: ^3.0.0
  image_gallery_saver: ^2.0.3
  flutter_image_compress: ^2.1.0
  youtube_player_iframe:
  webview_flutter: ^4.7.0
  flutter_inappwebview:
  connectivity_plus: ^5.0.2
  flutter_native_splash:
  firebase_messaging:
  firebase_core:
  flutter_app_badger: ^1.5.0
  firebase_core_platform_interface:
  open_mail_app: ^0.4.5
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  timezone: ^0.9.2
  vimeo_video_player:
  image_picker: ^1.0.7
  flick_video_player: ^0.5.0
  video_player: ^2.4.0
  dropdown_search: ^5.0.6
  flutter_widget_from_html: ^0.14.11
  intl: ^0.19.0
  network_info_plus: ^3.0.5
  fluttertoast: ^8.2.4
  flutter_screenutil: ^5.9.0
  flutter_datetime_picker_plus: ^2.2.0

flutter_icons:
  ios: true
  android: "launcher_icon"
  image_path: "assets/appicon.jpg"
  #image_path_ios: "assets/launcher/icon.png"
  #image_path_android: "assets/launcher/icon.png"
  #adaptive_icon_background: "assets/launcher/background.png"
  #adaptive_icon_foreground: "assets/launcher/foreground.png"

dependency_overrides:
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

flutter_native_splash:
  background_image: "assets/splashScreen.png"
  android_12:
